apiVersion: v1
kind: ConfigMap
metadata:
  name: rtmlib-ml-backend-config
  labels:
    app: rtmlib-ml-backend
data:
  # ML Backend Configuration
  BACKEND_PORT: "9090"
  DEVICE: "cpu"  # Change to "cuda" for GPU nodes
  BACKEND_TYPE: "onnxruntime"
  MODE: "balanced"  # performance, lightweight, balanced
  CONFIDENCE_THRESHOLD: "0.3"
  DEBUG: "false"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: label-studio-config-template
  labels:
    app: rtmlib-ml-backend
type: Opaque
stringData:
  # These will be overridden by GitHub Actions
  api-token: "your-label-studio-api-token"
  url: "http://label-studio-service:8080"
