apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: rtmlib-ml-backend-monitor
  labels:
    app: rtmlib-ml-backend
spec:
  selector:
    matchLabels:
      app: rtmlib-ml-backend
  endpoints:
  - port: http
    path: /health
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: rtmlib-ml-backend-metrics
  labels:
    app: rtmlib-ml-backend
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  selector:
    app: rtmlib-ml-backend
