apiVersion: v1
kind: Service
metadata:
  name: rtmlib-ml-backend-service
  labels:
    app: rtmlib-ml-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
    name: http
  selector:
    app: rtmlib-ml-backend