apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtmlib

resources:
- ../../  # Base manifests

patchesStrategicMerge:
- production-deployment-patch.yaml

commonLabels:
  environment: production

configMapGenerator:
- name: rtmlib-ml-backend-config
  behavior: replace
  literals:
  - DEVICE=cpu
  - BACKEND_TYPE=onnxruntime
  - MODE=balanced
  - LOG_LEVEL=INFO
  - DEBUG=false
  - CONFIDENCE_THRESHOLD=0.5

replicas:
- name: rtmlib-ml-backend
  count: 3
