apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rtmlib

resources:
- ../../  # Base manifests

patchesStrategicMerge:
- staging-deployment-patch.yaml

commonLabels:
  environment: staging

configMapGenerator:
- name: rtmlib-ml-backend-config
  behavior: replace
  literals:
  - DEVICE=cpu
  - BACKEND_TYPE=onnxruntime
  - MODE=balanced
  - LOG_LEVEL=DEBUG
  - DEBUG=true
  - CONFIDENCE_THRESHOLD=0.3

replicas:
- name: rtmlib-ml-backend
  count: 1
